Fix/new colours
nearform/quantum pull request #105
Opened 2023-11-03 11:21 UTC by Ademsk1

Adds in dark colour mode to the alias colour set. Applied to the current colours used.

2023-11-06 11:11 UTC, ergusto requested changes
Changes look good, but it seems to have broken the Storybook colors.md page. We could maybe also split the sections in that page up to reflect the categorisation of colours in the new folder structure.

2023-11-06 15:07 UTC, ergusto requested changes
Quite a few suggestions/change requests I'm afraid but mostly small things. I think we will be able to neaten up the colors.md page a bit as there's quite a lot of duplication there and I think we might be able to display it in a more useful/digestible format, but let's leave that for the time being.

2023-11-06 15:28 UTC, Ademsk1 commented on src/components/Checkbox/index.tsx
> +    'data-[state=checked]:border-primary-DEFAULT-600',
I have, they look good. I don't think we can apply DEFAULT to another object filled with colours to ignore it.

2023-11-06 16:05 UTC, ergusto requested changes
One more minor thing then good to go.

2023-11-06 16:05 UTC, ergusto commented on stories/Colors.mdx
> +<ColorWrapper colorPalette={aliasColors.button.danger} />
It looks like the `ColorWrapper` component isn't working for these three colour sets, it's rendering a blank colour swatch for `dark` where it isn't defined. 

Can we also simplify these success and danger colours and just have a single row for each?

2023-11-06 16:05 UTC, ergusto requested changes
One more minor thing then good to go.

2023-11-07 10:23 UTC, ergusto requested changes

2023-11-07 10:44 UTC, ergusto approved these changes

2023-11-07 10:44 UTC, merged