Feat/127 accordion
nearform/quantum pull request #227
Opened 2023-12-13 14:28 UTC by i-suman

2023-12-14 07:54 UTC, nherment requested changes
Looks good and works well. Some things do not seem to be to spec (see below):

- There seems to be a line between an unopened section followed by an opened one
- The Dark mode seems to be unimplemented.

![image](https://github.com/nearform/quantum/assets/1041426/6e42ffb2-ca59-4717-bf7c-b941f609b9aa)

![image](https://github.com/nearform/quantum/assets/1041426/b42b7dbe-9217-49f1-88e7-62d47665ab30)

2023-12-14 09:25 UTC, Ademsk1 submitted a review, later dismissed

2023-12-14 09:27 UTC, Ademsk1 reviewed
Don't forget to add this to `src/index.js` so it can be imported from.

2023-12-14 12:11 UTC, i-suman commented
> Looks good and works well. Some things do not seem to be to spec (see below):
> 
> * There seems to be a line between an unopened section followed by an opened one
> * The horizontal lines stop short of the edges of the component
> * The Dark mode seems to be unimplemented.
> 
> ![image](https://private-user-images.githubusercontent.com/1041426/290446795-6e42ffb2-ca59-4717-bf7c-b941f609b9aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NTYwNTAsIm5iZiI6MTcwMjU1NTc1MCwicGF0aCI6Ii8xMDQxNDI2LzI5MDQ0Njc5NS02ZTQyZmZiMi1jYTU5LTQ3MTctYmY3Yy1iOTQxZjYwOWI5YWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTRUMTIwOTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmY3MTgwMzVmNTEwYzE4NjE4NjdjNzM4NGE4M2E1M2JiNmU1YmMzYjhmZjMwYzI0OTBiMjUxNGM5YzRmYWIyMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-iOvr8aGr7zIxm_kjhLDK2dMi1ysBWA-AdDAkhHpWwg) ![image](https://private-user-images.githubusercontent.com/1041426/290447330-c4def775-c2ff-4cdf-93db-ef5df03e1547.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NTYwNTAsIm5iZiI6MTcwMjU1NTc1MCwicGF0aCI6Ii8xMDQxNDI2LzI5MDQ0NzMzMC1jNGRlZjc3NS1jMmZmLTRjZGYtOTNkYi1lZjVkZjAzZTE1NDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTRUMTIwOTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGU1ZGVmZjNhMWNmMWQzZmM0NTlmYWJmZjM4MDhjNDVhMmI1YTk4ZGI1NmFkZDg3MDE4MTA0NzliMTRhMmY5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GRDVJwnMWTuBAx3guvV_1jrRexpgbUq-QbvSz-yfjY8)
> 
> ![image](https://private-user-images.githubusercontent.com/1041426/290447151-b42b7dbe-9217-49f1-88e7-62d47665ab30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NTYwNTAsIm5iZiI6MTcwMjU1NTc1MCwicGF0aCI6Ii8xMDQxNDI2LzI5MDQ0NzE1MS1iNDJiN2RiZS05MjE3LTQ5ZjEtODhlNy02MmQ0NzY2NWFiMzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTRUMTIwOTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTk3ODJmMjdjZDgxNmVjZjE5ZTgzMzkyMDhlMWM5MGE0MjlkODRjM2M2NWE4ZTY3OWQ2Mjk3NDdkYjE5MjE2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._AuvJFPNnw7-Mz3xi0vpsO_k60fLA-Hs4ykTFghkSDU)

**Changes are done**



> Don't forget to add this to `src/index.js` so it can be imported from.

**Made it available**

2023-12-15 09:39 UTC, nherment approved these changes

2023-12-18 07:41 UTC, merged